### ISSUE TITLE
カレンダー削除後、一覧画面が最新状態にリフレッシュされない

### ISSUE THREAD

**Issue by hondaYoshitaka** [job-streamer/job-streamer-console#10]
【実行環境】
ブラウザ：　IE11

【再現手順】
1.カレンダー一覧画面に遷移する
2.任意のカレンダーを削除する
　→　画面上は削除されていないように見える
3. F5を押し、再描画する
　→　カレンダーが削除されている

【期待する動き】
削除後、削除されたカレンダーは一覧に表示されない

**Comment by seki-seki** [comment]
done.
