### ISSUE TITLE
ジョブ部品となるクラスが登録されていない場合、ジョブ新規作成するとレイアウトが崩れる

### ISSUE THREAD

**Issue by hondaYoshitaka** [job-streamer/job-streamer-console#2]

**Comment by seki-seki** [comment]
![console job new broken_layout](https://cloud.githubusercontent.com/assets/16893450/13419912/31ece074-dfc5-11e5-89d6-302047110e67.png)

再現方法:/#/jobs/newにてF5押下で発生
推測原因：jsでエラーがでているのでそのせいだと思われる

**Comment by seki-seki** [comment]
done.
