### ISSUE TITLE
右上メニューのjob,agent ボタンをクリックすると、クリックした回数分クリックしないと削除ができない

### ISSUE THREAD

**Issue by seki-seki** [job-streamer/job-streamer-console#22]
![agent_job](https://cloud.githubusercontent.com/assets/16893450/14449815/a3688f1a-00b2-11e6-850f-e48d2764e459.png)
agent /job などをクリック

![push_delete](https://cloud.githubusercontent.com/assets/16893450/14449845/06224344-00b3-11e6-8877-d5df17bcbc5a.png)
delete を複数回クリックしないと反応しない

**Comment by seki-seki** [comment]
開発環境のみで発生する可能性が高い
jarに固めると発生しなくなる？
確認待ち

**Comment by seki-seki** [comment]
ver 1.3.0にてjarに固めても発生することを確認
対応必須か。。。

**Comment by hondaYoshitaka** [comment]
I'd like to ask that you write a description of the reproduction conditions.
