### ISSUE TITLE
Agent画面のCPU, メモリ状況の画像表示が[x]で表示される

### ISSUE THREAD

**Issue by hondaYoshitaka** [job-streamer/job-streamer-console#3]

**Comment by seki-seki** [comment]
とくにコード変更なく、ある日突然画像が表示されるようになっていたらしいです。
クローズでよいのでしょうか・・・

**Comment by hondaYoshitaka** [comment]
I can't reproduce the error.

following version:
- bus: 0.3.0
- console: 0.3.0
- agent: 0.3.0-beta1

so, I think you can close this issue.
