### ISSUE TITLE
there is Inadequacy in exclusive execution control area

### ISSUE THREAD

**Issue by seki-seki** [job-streamer/job-streamer-console#38]
①チェックマークの表示不備
②多重実行制御のボタン背景色表示不備

①チェックマークの表示
　　IE : 表示　Firefox : 非表示
②多重実行制御の状態
　　IE : 設定状態保存できる　Firefox : 設定状態保存できない

**Comment by seki-seki** [comment]
firefoxは反応がおそいっぽいですね
2～3秒待ってみてください

**Comment by seki-seki** [comment]
お客様勘違いではないかと・・・
確認をお願いします

**Comment by hondaYoshitaka** [comment]
どのような点に関して確認が必要か教えてください。

**Comment by seki-seki** [comment]
1.お客様環境のfirefox で多重制御ボタンをクリック
2.チェックが青くなり（チェック済みの状態）、右にチェックマークが表示されるまで（2~3秒）待つ
3.タブをhistoryなどに変更し、再度settingsに戻る
4.しばらく待ち、チェックが青くなることを確認する。

**Comment by hondaYoshitaka** [comment]
firefox では2~3秒待つのが仕様となる、ということかな？
もしそうしたいのであれば、UIとしては分かりにくいのである程度の落とし所が必要。

手始めに以下のどちらに原因があるのかを切り分ける必要がある。
　・FireFoxのレンダリングの仕様
　・実装上の問題
話はそれからになるかな。

**Comment by seki-seki** [comment]
【チェックマークが表示されるのに時間がかかる理由】
firefoxで数秒待たないといけない理由はpreflightのレスポンスに時間がかかる場合が多いからである。
当該事象はcontrol-bus側の問題なのでcontrol-bus側のissueに挙げた。
https://github.com/job-streamer/job-streamer-control-bus/issues/5
また、当該事象はpreflightを行うすべてのブラウザで発生する。
【行ったこと】
preflightを行うブラウザのpreflightにかかる時間を調べた。（画像はchromeのもの）
![preflight-too-long](https://cloud.githubusercontent.com/assets/16893450/15886686/57456892-2d99-11e6-8d2e-fc94b1749238.png)
【結果】
preflightに時間がかかっているため、チェックマークなどが表示されるのに時間がかかることがわかった。
