### ISSUE TITLE
同名カレンダー登録において、バリデーションをすり抜け保存ボタンのアクションを実行できてしまう

### ISSUE THREAD

**Issue by hondaYoshitaka** [job-streamer/job-streamer-console#48]
同名のカレンダー登録/更新において 同名チェックのバリデーションをすり抜けて保存ボタンを押すことができる。ただし、実際に保存は行われていない模様（UI上は保存のチェックマークがでるだけ？）。
# 事象が発生する前提
- console:0.4.0
# 再現手順
1. カレンダー「ABC」を作成し、保存ボタンを押す
2. 再度、カレンダー作成画面に遷移する
3. カレンダー名に「ABC」と入力する→バリデーションにかかる
4. カレンダー名からフォーカスを外す
5. カレンダー名にフォーカスを合わす→バリデーションpopupが消える
6. Saveボタンを押す
# 期待する挙動（案）
- 新規/更新において 保存時に再度バリデーションを実施する
- 保存のチェックマークはサーバに保存された後に表示する

**Comment by seki-seki** [comment]
ジョブと挙動をあわせる目的、また将来的に追加されるであろうカレンダーのimport/export機能に備え、control-busサーバー側ではバリデーションは行いません。（同名が入力された場合上書きが正）

そのため、再度フォーカスされた場合バリデーションpopupを消さないように修正しました。
https://github.com/job-streamer/job-streamer-console/pull/50
