### ISSUE TITLE
New job's sort order does not locate first

### ISSUE THREAD

**Issue by hondaYoshitaka** [job-streamer/job-streamer-console#49]
detail is https://github.com/job-streamer/job-streamer-control-bus/issues/8

**Comment by seki-seki** [comment]
デフォルトで最近作られた要素が上に来るようにしました。
(内部的に振られているidの降順)
https://github.com/job-streamer/job-streamer-control-bus/pull/7

**Comment by seki-seki** [comment]
ソート機能は次のリリースに間に合うかわかりませんが、いつか作りたいですね

**Comment by seki-seki** [comment]
There is search function

**Comment by seki-seki** [comment]
世界的にデフォルトとして、ソートすることは正しいのか、chronosを確認して
正しければ再度プルリクを送ります。
