### ISSUE TITLE
カレンダ登録画面でSaveボタン下に 謎の数字が表示される

### ISSUE THREAD

**Issue by hondaYoshitaka** [job-streamer/job-streamer-console#6]

**Comment by seki-seki** [comment]
再現手順：
1.任意の名前でカレンダーを登録する。
![console calendars new number_under_save_button1](https://cloud.githubusercontent.com/assets/16893450/13420404/4b65aa78-dfc9-11e5-95b6-e12b9aedd4d5.png)
2.一度カレンダー一覧画面に戻る。(この時、手順1で登録したカレンダーを削除しても再現する。)
3.再度カレンダー新規作成画面に移行後、手順1で登録した名前で再登録
![console calendars new number_under_save_button2](https://cloud.githubusercontent.com/assets/16893450/13420471/d7e36792-dfc9-11e5-93ba-86a168fa244b.png)
