### ISSUE TITLE
ジョブ詳細画面でQuartz形式で登録した情報が 確認できない(No Schedule表示となる)

### ISSUE THREAD

**Issue by hondaYoshitaka** [job-streamer/job-streamer-console#7]

**Comment by seki-seki** [comment]
再現手順：
1.ジョブとカレンダーを最低ひとつずつ作成し、ジョブ詳細画面に遷移
2.Quartz形式もしくはカレンダーを選択し、saveを押下する。
![console job cant_save_schedule](https://cloud.githubusercontent.com/assets/16893450/13446807/e66c4d16-e059-11e5-9c9d-bf88bbf08f03.png)

**Comment by seki-seki** [comment]
上記コミットにて修正済みかと思います。
確認をお願いします。
