### ISSUE TITLE
When push jobs list view -> "Started at" during job executing,  accordion is arbitrarily closed

### ISSUE THREAD

**Issue by hondaYoshitaka** [job-streamer/job-streamer-console#8]
【再現手順】
1. 任意の2つのジョブを用意する（ジョブA、ジョブB）
2.ジョブAを手動実行する
　→　処理中となる
3.ジョブBの「Started at」項目の日付を押す
　→ ステップ詳細のアコーディオンが開く
　⇒ が、直後すぐ閉じてしまう

【期待する動き】
・ジョブ実行中であってもアコーディオンの開閉状態を維持する

**Comment by seki-seki** [comment]
【調査結果】
job->job/latest-execution->job-execution/step-executions が空でなければアコーディオンは開いた状態となる。
しかし、ジョブ実行中はジョブの終了を判定するために定期的にジョブの状態と画面を更新している。
更新の際にjob->job/latest-execution->job-execution/step-executionsが空になってしまうため、本件が発生している。
修正には大幅に設計を見直さないといけない。

**Comment by seki-seki** [comment]
本件は見送りです
